name: LaTeX

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_shell_escape: true
          
      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
